In [20]:
import numpy as np

n = 4
U = np.triu(np.random.randn(n,n), 0)
b = np.random.randn(n,1)

def BS_solve(U, b):
    temp = np.copy(b)
    x = np.zeros((len(U),1))
    for i in reversed(range(len(U))): # 3 2 1 0
        for j in reversed(range(i,len(U))):
            if (j > i):
                temp[i] -= U[i,j] * x[j]
            else:
                x[i] = temp[i]/U[i,j]
    return x

print("U: ")
print(U, '\n')
print("b: ")
print(b, '\n')
x = BS_solve(U, b)
print("x: ")
print(x, '\n')
print("Distance: ", np.linalg.norm(b-np.dot(U,x)))


U: 
[[-1.68120004 -2.58044872 -0.85281116  0.59244566]
 [ 0.          0.60945601  0.54485546 -1.01144273]
 [ 0.          0.          1.41607846  0.25245048]
 [ 0.          0.          0.          0.04458358]] 

b: 
[[-3.51532468e-01]
 [ 5.83763075e-01]
 [-1.58834322e+00]
 [-7.86885912e-04]] 

x: 
[[-2.18976829]
 [ 1.92849641]
 [-1.11850268]
 [-0.01764968]] 

Distance:  2.5438405243138006e-16
